### ISSUE TITLE
rs change star 模型调用出错

### ISSUE THREAD

**Issue by HaitaoWuTJU** [PaddleCV-SIG/PaddleRS#58]
model=pdrs.tasks.ChangeStar(
    num_classes=2,
    use_mixed_loss=False,
    mid_channels=256,
    inner_channels=16,
    num_convs=4,
    scale_factor=4.0,
)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_160/3661388624.py in <module>
      5     inner_channels=16,
      6     num_convs=4,
----> 7     scale_factor=4.0,
      8 )

~/PaddleRS/paddlers/tasks/changedetector.py in __init__(self, num_classes, use_mixed_loss, mid_channels, inner_channels, num_convs, scale_factor, **params)
    883             num_classes=num_classes,
    884             use_mixed_loss=use_mixed_loss,
--> 885             **params)
    886 
    887     def default_loss(self):

~/PaddleRS/paddlers/tasks/changedetector.py in __init__(self, model_name, num_classes, use_mixed_loss, **params)
     61         if params.get('with_net', True):
     62             params.pop('with_net', None)
---> 63             self.net = self.build_net(**params)
     64         self.find_unused_parameters = True
     65 

~/PaddleRS/paddlers/tasks/changedetector.py in build_net(self, **params)
     67         # TODO: add other model
     68         net = cmcd.__dict__[self.model_name](num_classes=self.num_classes,
---> 69                                              **params)
     70         return net
     71 

~/PaddleRS/paddlers/custom_models/cd/changestar.py in __init__(self, num_classes, mid_channels, inner_channels, num_convs, scale_factor)
    138             inner_channels=inner_channels,
    139             num_convs=num_convs,
--> 140             scale_factor=scale_factor)
    141 
    142 

~/PaddleRS/paddlers/custom_models/cd/changestar.py in __init__(self, seg_model, num_classes, mid_channels, inner_channels, num_convs, scale_factor)
     29     def __init__(self, seg_model, num_classes, mid_channels, inner_channels,
     30                  num_convs, scale_factor):
---> 31         super(_ChangeStarBase, self).__init__(_ChangeStarBase, self)
     32 
     33         self.extract = seg_model

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py in __init__(self, name_scope, dtype)
    103         if name_scope is None:
    104             name_scope = _convert_camel_to_snake(self.__class__.__name__)
--> 105         self._full_name = unique_name.generate(name_scope)
    106         self._helper = LayerObjectHelper(self._full_name)
    107         self._built = False

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/unique_name.py in generate(key)
    103             print(name1, name2) # fc_0, fc_1
    104     """
--> 105     return generator(key)
    106 
    107 

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/unique_name.py in __call__(self, key)
     49         tmp = self.ids[key]
     50         self.ids[key] += 1
---> 51         return self.prefix + "_".join([key, str(tmp)])
     52 
     53 

TypeError: sequence item 0: expected str instance, type found

**Comment by Bobholamovic** [comment]
这个bug在近期的commit中修复了，请更新到最新版本后再次尝试。

**Comment by Bobholamovic** [comment]
你好，如果问题解决了，可以麻烦关闭这个issue么？

**Comment by HaitaoWuTJU** [comment]
好的
