### ISSUE TITLE
PaddleRS如何在windows上使用？

### ISSUE THREAD

**Issue by CuZaoo** [PaddleCV-SIG/PaddleRS#80]
我在windows上用PyCharm上安装了paddle
但是import paddlers as pdrs 会报错
是要安装paddlers么？
具体要怎么安装呢？
pip install paddlers貌似无效

**Comment by henryccl** [comment]
你好！我也是在window上安装出错，无法import paddlers as pdrs
请问你解决这个问题了吗？

**Comment by Bobholamovic** [comment]
> 你好！我也是在window上安装出错，无法import paddlers as pdrs 请问你解决这个问题了吗？

可以说一下具体的问题吗？提供报错信息、环境信息、复现条件等等。
