### ISSUE TITLE
预测的时候出现错误

### ISSUE THREAD

**Issue by kimho0220** [PaddleCV-SIG/PaddleRS#81]
![Q_T0)DBSCOF00ANY_ZQPI_V](https://user-images.githubusercontent.com/82701518/167102590-1197eb6f-b392-4379-a7b3-17acafcadac8.png)

**Comment by Bobholamovic** [comment]
预处理阶段使用的归一化参数（均值、标准差）和测试影像的波段数是否匹配呢？

**Comment by kimho0220** [comment]
W0506 18:51:05.712293  4288 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 11.2
W0506 18:51:05.722298  4288 device_context.cc:465] device: 0, cuDNN Version: 8.1.
W0506 18:51:06.451321  4288 device_context.h:397] WARNING: device: 0. The installed Paddle is compiled with CUDNN 8.2, but CUDNN version in your machine is 8.1, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
2022-05-06 18:51:07 [INFO]	Loading pretrained model from ./output/unet/pretrain\model.pdparams
2022-05-06 18:51:07 [WARNING]	[SKIP] Shape of pretrained params encode.double_conv.0._conv.weight doesn't match.(Pretrained: [64, 3, 3, 3], Actual: [64, 10, 3, 3])
2022-05-06 18:51:07 [WARNING]	[SKIP] Shape of pretrained params cls.weight doesn't match.(Pretrained: [19, 64, 3, 3], Actual: [5, 64, 3, 3])
2022-05-06 18:51:07 [WARNING]	[SKIP] Shape of pretrained params cls.bias doesn't match.(Pretrained: [19], Actual: [5])
2022-05-06 18:51:07 [WARNING]	[SKIP] Shape of pretrained params conv.weight doesn't match.(Pretrained: [19, 64, 3, 3], Actual: [5, 64, 3, 3])
2022-05-06 18:51:07 [WARNING]	[SKIP] Shape of pretrained params conv.bias doesn't match.(Pretrained: [19], Actual: [5])
2022-05-06 18:51:07 [INFO]	There are 107/112 variables loaded into UNet.
Warning 1: ./data/rsseg/remote_sensing_seg/data\LC80500162014247LGN00_21_data.tif: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
Warning 1: ./data/rsseg/remote_sensing_seg/data\LC82151102013360LGN00_26_data.tif: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.


训练的时候报这样的warning 。下下来预处理什么的代码都没改 测试图考了一个训练集的4通道的也不行用3通道的图也不行

**Comment by Bobholamovic** [comment]
请问是跑的tutorials中的教程吗？还是说在哪个教程的基础上做了修改，比如用的是自己的数据呢？

**Comment by kimho0220** [comment]
就是tutorials中的unet 代码,除了做一些读取路径的更改无任何改动，数据集是运行PaddleRS-develop\tutorials\train\semantic_segmentation\unet.py自己下的, 有上述warning 但是可以训练，训练得到的best_model也按照部署要求做了变成inference_model文件的转换

**Comment by Bobholamovic** [comment]
训练时报的那些警告是正常的情况。测试时需要使用10通道的数据，因为训练集的数据是10通道的。

**Comment by kimho0220** [comment]
10通道的数据是 数据集文件里的  .tif 文件吧 （）
![image](https://user-images.githubusercontent.com/82701518/167131024-52d8a7ba-f81c-4dd0-bf8b-86b711e9868b.png)

如果用那个预测会有如下错误
 
    File "C:\Users\10729\anaconda3\envs\PaddleRS\lib\site-packages\paddle\fluid\framework.py", line 2224, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 10, the input's shape is [1, 10, 512, 512]; the filter's channels is 3, the filter's shape is [64, 3, 3, 3]; the groups is 1, the data_format is NCHW. The error may come from wrong data_format setting.
      [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:10 != filter_dims[1] * groups:3.] (at ..\paddle/fluid/operators/conv_op.cc:119)
      [operator < conv2d > error]

**Comment by kimho0220** [comment]
对了 我在训练时因为GPU跑不了4更改了batchsize，改为了3 是这个影响吗

**Comment by Bobholamovic** [comment]
> 对了 我在训练时因为GPU跑不了4更改了batchsize，改为了3 是这个影响吗

今天复查了代码发现导出部分确实存在bug，目前正在修复中 #85 ，请耐心等待~

**Comment by kimho0220** [comment]
修复了吗？今天重新下了代码跑，还是这个问题。。。
用图data\rsseg\remote_sensing_seg\data_vis 里面的会这样
![image](https://user-images.githubusercontent.com/82701518/168034126-31182b5b-db95-44c1-b67e-d858ab5164ea.png)
用图data\rsseg\remote_sensing_seg\data里面的会这样
    File "C:\Users\10729\anaconda3\envs\PaddleRS\lib\site-packages\paddle\fluid\framework.py", line 2224, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 10, the input's shape is [1, 10, 512, 512]; the filter's channels is 3, the filter's shape is [64, 3, 3, 3]; the groups is 1, the data_format is NCHW. The error may come from wrong data_format setting.
      [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:10 != filter_dims[1] * groups:3.] (at ..\paddle/fluid/operators/conv_op.cc:119)
      [operator < conv2d > error]

**Comment by Bobholamovic** [comment]
已经提了修复的PR，正在review中，请耐心等待。在[此处](https://github.com/PaddleCV-SIG/PaddleRS/pull/85)查看review进度。

**Comment by Bobholamovic** [comment]
PR已合入。请拉取develop分支的最新commit并再次尝试，导出模型推理时的通道数问题应该可以解决。此外，如果您不希望在训练时看到大量的GDAL警告，可以使用`tutorials/train/semantic_segmentation/run_with_clean_log.py`脚本滤除这些警告，具体用法为：

```bash
# 以UNet训练为例
# 因技术原因，run_with_clean_log.py脚本暂不支持多卡训练
python run_with_clean_log.py unet.py
```

**Comment by kimho0220** [comment]
最新版的导出直接出错了

    ValueError: (InvalidArgument) The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 3, the input's shape is [-1, 3, -1, -1]; the filter's channels is 10, th
e filter's shape is [64, 10, 3, 3]; the groups is 1, the data_format is NCHW. The error may come from wrong data_format setting.
  [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:3 != filter_dims[1] * groups:10.] (at ..\paddle/fluid/operators/conv_op.cc:119)
  [operator < conv2d > error]

**Comment by Bobholamovic** [comment]
> 最新版的导出直接出错了
> 
> ```
> ValueError: (InvalidArgument) The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 3, the input's shape is [-1, 3, -1, -1]; the filter's channels is 10, th
> ```
> 
> e filter's shape is [64, 10, 3, 3]; the groups is 1, the data_format is NCHW. The error may come from wrong data_format setting. [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:3 != filter_dims[1] * groups:10.] (at ..\paddle/fluid/operators/conv_op.cc:119) [operator < conv2d > error]

是UNet吗？请给出导出模型时使用的指令。

**Comment by kimho0220** [comment]
是的 指令如下 
python deploy/export/export_model.py --model_dir=./tutorials/train/semantic_segmentation/output/unet/best_model/ --save_dir=./tutorials/train/semantic_segmentation/output/unet/inference_model/

**Comment by kimho0220** [comment]
> > 最新版的导出直接出错了
> > ```
> > ValueError: (InvalidArgument) The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 3, the input's shape is [-1, 3, -1, -1]; the filter's channels is 10, th
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > e filter's shape is [64, 10, 3, 3]; the groups is 1, the data_format is NCHW. The error may come from wrong data_format setting. [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:3 != filter_dims[1] * groups:10.] (at ..\paddle/fluid/operators/conv_op.cc:119) [operator < conv2d > error]
> 
> 是UNet吗？请给出导出模型时使用的指令。

是的 指令如下
python deploy/export/export_model.py --model_dir=./tutorials/train/semantic_segmentation/output/unet/best_model/ --save_dir=./tutorials/train/semantic_segmentation/output/unet/inference_model/

**Comment by kimho0220** [comment]
这是路径下的图

![image](https://user-images.githubusercontent.com/82701518/169791841-e7fe43b3-8ad3-441e-9f6a-6e7b27d5e56f.png)

**Comment by Bobholamovic** [comment]
> 

因为tutorial是10通道的数据，所以请在导出模型时显式指定`--fixed_input_shape`选项，具体可参见[导出教程](https://github.com/PaddleCV-SIG/PaddleRS/tree/develop/deploy/export)。
