### ISSUE TITLE
Can't use paddle's ReduceOnPlateau

### ISSUE THREAD

**Issue by Xeladoes** [PaddleCV-SIG/PaddleRS#88]
paddle.optimizer.lr.ReduceOnPlateau.step(metrics, epoch=None), it require metrics that other paddle.optimizer.lr doesn't;

when you use ReduceOnPlateau as learning rate scheduler like this:
--------------------------------------
model = pdrs.tasks.BIT(...
lr_scheduler = paddle.optimizer.lr.ReduceOnPlateau(
    LR, 
)
optimizer = paddle.optimizer.Adam(
    learning_rate=lr_scheduler,
    parameters=model.net.parameters()
)
model.train(...
--------------------------------------
it will rise a TypeError: step() missing 1 required positional argument: 'metrics'

**Comment by Bobholamovic** [comment]
Official reply: Currently, PaddleRS does **NOT** support `paddle.optimizer.lr.ReduceOnPlateau()`.  We are considering adding this feature in the future.

---

*For Geeks who want to hack the source code:* 

Change this line of code:

https://github.com/PaddleCV-SIG/PaddleRS/blob/f81809d12730aa941958bf2b9c219d7cdb815fe6/paddlers/tasks/base.py#L376

Pass an indicator (which should be some metric, see [the doc](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/optimizer/lr/ReduceOnPlateau_en.html)) to `step()` when calling it.

**Comment by geoyee** [comment]
@Bobholamovic 晖哥应该这样加上就行 https://github.com/PaddlePaddle/PaddleSeg/pull/1658

**Comment by Bobholamovic** [comment]
We have added this feature in #107 . Please pull the latest version of the develop branch before using `paddle.optimizer.lr.ReduceOnPlateau`.
