### ISSUE TITLE
变化检测预测

### ISSUE THREAD

**Issue by lihaoming152221** [PaddleCV-SIG/PaddleRS#89]
![识别结果](https://user-images.githubusercontent.com/69884343/168758830-80d902f9-e7e0-4b7a-8c5e-15f0eee9fd06.png)
输出的这结果正常吗？

**Comment by Bobholamovic** [comment]
看起来是正常的，`score_map`是两通道变化概率图（第二个通道为变化概率)，`label_map`是二值变化图。

**Comment by lihaoming152221** [comment]
一般训练多少轮预测的结果比较好呢？

**Comment by Bobholamovic** [comment]
这个问题不好回答，根据不同的上下文可能有不同的答案。总体而言，您可以通过训练/验证loss曲线判断模型的性能。

**Comment by lihaoming152221** [comment]
识别的时候传入的图片格式有要求吗？

**Comment by lihaoming152221** [comment]
识别后的结果完全不对呀

**Comment by lihaoming152221** [comment]
![20220523150018](https://user-images.githubusercontent.com/69884343/169762006-96763e8d-88ba-40ab-b5ad-282ccdb5c07c.png)

**Comment by Bobholamovic** [comment]
请提供具体的复现方式和版本、配置信息等。

**Comment by lihaoming152221** [comment]
import paddlers as pdrs
import numpy as np
from PIL import Image

# 将导出模型所在目录传入Predictor的构造方法中
predictor = pdrs.deploy.Predictor('./inference_model')
# img_file参数指定输入图像路径
result = predictor.predict(img_file=('train_2.png', 'train__2.png'))
print(result)

ar = result[0]['label_map']
print(ar, type(ar))
ar[ar > 0] = 255
arr = np.array(ar, dtype='uint8')
arr = Image.fromarray(arr)
arr.save('test.bmp', 'bmp')

模型导出后
我用这个方法生成了bmp格式的图片
Package               Version
--------------------- ---------
astor                 0.8.1
Babel                 2.10.1
bce-python-sdk        0.8.64
certifi               2021.10.8
cfgv                  3.3.1
chardet               4.0.0
charset-normalizer    2.0.12
click                 8.1.3
colorama              0.4.4
cycler                0.11.0
Cython                0.29.28
decorator             5.1.1
distlib               0.3.4
easydict              1.9
et-xmlfile            1.1.0
filelock              3.6.0
flake8                4.0.1
Flask                 2.1.2
Flask-Babel           2.0.0
fonttools             4.33.3
future                0.18.2
GDAL                  3.2.3
geojson               2.5.0
identify              2.5.0
idna                  3.3
imageio               2.19.1
importlib-metadata    4.2.0
itsdangerous          2.1.2
Jinja2                3.1.2
joblib                1.1.0
kiwisolver            1.4.2
lap                   0.4.0
llvmlite              0.36.0
MarkupSafe            2.1.1
matplotlib            3.5.2
mccabe                0.6.1
motmetrics            1.2.5
munch                 2.5.0
natsort               8.1.0
networkx              2.6.3
nodeenv               1.6.0
numba                 0.53.1
numpy                 1.19.3
opencv-contrib-python 4.3.0.38
opencv-python         4.5.5.64
openpyxl              3.0.9
packaging             21.3
paddlepaddle          2.2.2
paddlers              0.0.1
paddleslim            2.2.2
pandas                1.3.5
Pillow                9.1.0
pip                   22.0.4
platformdirs          2.5.2
pre-commit            2.19.0
protobuf              3.20.1
pycocotools           2.0.4
pycodestyle           2.8.0
pycryptodome          3.14.1
pyflakes              2.4.0
pyparsing             3.0.8
python-dateutil       2.8.2
pytz                  2022.1
PyWavelets            1.3.0
PyYAML                6.0
pyzmq                 22.3.0
requests              2.27.1
scikit-image          0.19.2
scikit-learn          0.23.2
scipy                 1.7.3
setuptools            62.1.0
Shapely               1.8.2
shellcheck-py         0.8.0.4
six                   1.16.0
threadpoolctl         3.1.0
tifffile              2021.11.2
toml                  0.10.2
tqdm                  4.64.0
typing_extensions     4.2.0
urllib3               1.26.9
virtualenv            20.14.1
visualdl              2.2.3
Werkzeug              2.1.2
xmltodict             0.13.0
zipp                  3.8.0

**Comment by lihaoming152221** [comment]
import paddlers as pdrs
import numpy as np
from PIL import Image

predictor = pdrs.deploy.Predictor('./inference_model')
result = predictor.predict(img_file=('train_2.png', 'train__2.png'))
print(result)

ar = result[0]['label_map']
print(ar, type(ar))
ar[ar > 0] = 255
arr = np.array(ar, dtype='uint8')
arr = Image.fromarray(arr)
arr.save('test.bmp', 'bmp')

我用这个方法生成了bmp格式的图片
Package               Version
--------------------- ---------
astor                 0.8.1
Babel                 2.10.1
bce-python-sdk        0.8.64
certifi               2021.10.8
cfgv                  3.3.1
chardet               4.0.0
charset-normalizer    2.0.12
click                 8.1.3
colorama              0.4.4
cycler                0.11.0
Cython                0.29.28
decorator             5.1.1
distlib               0.3.4
easydict              1.9
et-xmlfile            1.1.0
filelock              3.6.0
flake8                4.0.1
Flask                 2.1.2
Flask-Babel           2.0.0
fonttools             4.33.3
future                0.18.2
GDAL                  3.2.3
geojson               2.5.0
identify              2.5.0
idna                  3.3
imageio               2.19.1
importlib-metadata    4.2.0
itsdangerous          2.1.2
Jinja2                3.1.2
joblib                1.1.0
kiwisolver            1.4.2
lap                   0.4.0
llvmlite              0.36.0
MarkupSafe            2.1.1
matplotlib            3.5.2
mccabe                0.6.1
motmetrics            1.2.5
munch                 2.5.0
natsort               8.1.0
networkx              2.6.3
nodeenv               1.6.0
numba                 0.53.1
numpy                 1.19.3
opencv-contrib-python 4.3.0.38
opencv-python         4.5.5.64
openpyxl              3.0.9
packaging             21.3
paddlepaddle          2.2.2
paddlers              0.0.1
paddleslim            2.2.2
pandas                1.3.5
Pillow                9.1.0
pip                   22.0.4
platformdirs          2.5.2
pre-commit            2.19.0
protobuf              3.20.1
pycocotools           2.0.4
pycodestyle           2.8.0
pycryptodome          3.14.1
pyflakes              2.4.0
pyparsing             3.0.8
python-dateutil       2.8.2
pytz                  2022.1
PyWavelets            1.3.0
PyYAML                6.0
pyzmq                 22.3.0
requests              2.27.1
scikit-image          0.19.2
scikit-learn          0.23.2
scipy                 1.7.3
setuptools            62.1.0
Shapely               1.8.2
shellcheck-py         0.8.0.4
six                   1.16.0
threadpoolctl         3.1.0
tifffile              2021.11.2
toml                  0.10.2
tqdm                  4.64.0
typing_extensions     4.2.0
urllib3               1.26.9
virtualenv            20.14.1
visualdl              2.2.3
Werkzeug              2.1.2
xmltodict             0.13.0
zipp                  3.8.0

**Comment by Bobholamovic** [comment]
具体是哪一个模型呢？

**Comment by lihaoming152221** [comment]
DSIFN

**Comment by Bobholamovic** [comment]
> import paddlers as pdrs import numpy as np from PIL import Image
> 
> predictor = pdrs.deploy.Predictor('./inference_model') result = predictor.predict(img_file=('train_2.png', 'train__2.png')) print(result)
> 
> ar = result[0]['label_map'] print(ar, type(ar)) ar[ar > 0] = 255 arr = np.array(ar, dtype='uint8') arr = Image.fromarray(arr) arr.save('test.bmp', 'bmp')
> 
> 我用这个方法生成了bmp格式的图片 Package Version

提供的代码包括对`Predictor`的构造和使用以及可视化、存图的部分都是正确的。但我在本地无法复现您碰到的问题。请首先核对动态图和静态图的效果是否一致，如果确认是导出后才出现的问题，**请使用最新版本的PaddleRS重新训练模型**，参考[官方教程](https://github.com/PaddleCV-SIG/PaddleRS/tree/develop/deploy/export)，确认模型导出的部分是否存在错误。

**Comment by lihaoming152221** [comment]
ok

**Comment by lihaoming152221** [comment]
![27173147](https://user-images.githubusercontent.com/69884343/170673548-b475caff-d91e-45eb-bb8b-6e0dcbcc28e9.png)
这错误啥原因？

**Comment by Bobholamovic** [comment]
很可能是使用旧版PaddleRS训练模型、新版PaddleRS执行推理导致的。解决办法是手工删去yml文件中的`is_scale`字段。
